### ISSUE TITLE
Issue while installing on mac

### ISSUE THREAD

**Issue by kulkarnigovind9** [ueokande/logbook#6]
Hi,
I am having an issue while running the command `go get -u github.com/ueokande/logbook`, first it is taking a long time and doesn't give any output. And when I ran the command `logbook` it is throwing error `logbook: command not found`.
Could anyone help me?

**Comment by ueokande** [comment]
@kulkarnigovind9 
Did you set `$GOPATH/bin` into your environment variable `PATH`?

**Comment by kulkarnigovind9** [comment]
@ueokande 
Thanks, I missed that step. now I am able to use it.

Thanks a lot.
